### ISSUE TITLE
additional public lists of malicious URLs?

### ISSUE THREAD

**Issue by Apexgh0st** [stamparm/blackbook#6]
Hi,

Fan of your work, wondering if these lists are good additions to your project, Thanks.

https://threatshare.io/
http://0btemoslab.com/

**Comment by stamparm** [comment]
Hi.

1) Could do the https://threatshare.io/
2) http://0btemoslab.com/ is not friendly for scripting (i.e. it doesn't like programmatic content retrieval)

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/151776944-29897b00-4aa2-4c40-8435-f6d8577d96e3.png)
