### ISSUE TITLE
Shikitega C&C

### ISSUE THREAD

**Issue by ghost** [stamparm/blackbook#7]
Please add dash.cloudflare.ovh and main.cloudfronts.net, C&C for the new [Shikitega malware](https://cybersecurity.att.com/blogs/labs-research/shikitega-new-stealthy-malware-targeting-linux)

**Comment by stamparm** [comment]
blackbook is used only for automated C2 retrieval from known feeds. For these ^^ kind of C2s, we use maltrail. Look at https://github.com/stamparm/maltrail/blob/master/trails/static/malware/elf_shikitega.txt
