### ISSUE TITLE
Invalid domain

### ISSUE THREAD

**Issue by uro666** [stamparm/blackbook#8]
Hello,

There is a malformed domain in the blackbook lists, I only noticed it as I use the plaintext blackbook.txt list in my pi-hole as a domain AdList/Blacklist to sinkhole the domains and after a recent update it highlighted the invalid domain within it's adlist page.

The offending domain on line 15216 in the current commit 5ad67c2 is: 

`eweimce?z0c_#p.c_m `

This domain was added to the blackbook.csv list way back on the 15/01/2019 commit 76a224f line 19
It was introduced to the blackbook.txt list when you started producing the plain-text version of the csv list on 20/09/2019 commit 1ec11f0 line 6925

You can check the commit history to find when it was first introduced yourself by entering the following in a shell within the repository directory:

git log --all -p --reverse --source -S 'eweimce?z0c_#p.c_m'

The above git command will reverse search the commit history from oldest to newest and print out the commit data matching the quoted string after the -S parameter from within each of the commited files where it first finds a match of the string.

**Comment by stamparm** [comment]
thx :)

**Comment by uro666** [comment]
No problem, thanks for the quick fix 👍
